### Post SNS messages to the Street Manager Relay API
POST http://localhost:8080/v1/street-manager-relay/sns
Content-Type: application/json
x-amz-sns-message-type: 2

< ./data/2025-08-08/32933.570.json


### Search for activities within a bounding box
GET http://localhost:8080/v1/street-manager-relay/search?bbox=418141,421232,441633,445228
Accept: application/json;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip,deflate
Connection: keep-alive
Origin: https://foo.example


### Health check for the API
GET http://localhost:8080/healthz
Accept: application/json


### Prometheus metrics endpoint
GET http://localhost:8080/metrics