### Post SNS messages (activity) to the Street Manager Relay API
POST http://localhost:8080/v1/street-manager-relay/sns
Content-Type: application/json
x-amz-sns-message-type: 2

< ./data/2025-08-08/activities/32933.570.json


### Post SNS messages (permit) to the Street Manager Relay API
POST http://localhost:8080/v1/street-manager-relay/sns
Content-Type: application/json
x-amz-sns-message-type: 2

< ./data/2025-08-08/permits/32936.929.json


### Post SNS messages (section-58) to the Street Manager Relay API
POST http://localhost:8080/v1/street-manager-relay/sns
Content-Type: application/json
x-amz-sns-message-type: 2

< ./data/2025-08-08/section-58/34281.354.json


### Search for events within a bounding box
GET http://localhost:8080/v1/street-manager-relay/search?bbox=418995,435778,429089,441777&work_status_ref=planned&work_category_ref=paa
Accept: application/json;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip,deflate
Connection: keep-alive
Origin: https://foo.example


### Reference Data
GET http://localhost:8080/v1/street-manager-relay/refdata
Accept: application/json;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip,deflate
Connection: keep-alive
Origin: https://foo.example

### Health check for the API
GET http://localhost:8080/healthz
Accept: application/json


### Prometheus metrics endpoint
GET http://localhost:8080/metrics